namespace: "ibm"
name: "ibm-cloud"
version: "1.0.0"
readme: "README.md"
authors:
    - "Umar Ali"
description: "Ansible modules collection for IBM-Cloud."
license:
    - "MPL-2.0"
issues: "https://github.com/IBM-Cloud/community.ansible.ibm.cloud/issues"
tags:
    - ibmcloud
    - cloud
    - collection
    - ansible
repository: "https://github.com/IBM-Cloud/community.ansible.ibm.cloud"